### PR TITLE
(ios) App Access Control: Device passcode fallback

### PR DESCRIPTION
**Pull request by robbiehanson**
Partially addresses issue #441

> Phoenix should provide more options for app access control, each with their own trade-offs:
> 
> 1. biometrics authentication: the recommended option. It enables fine-grained control on a device that is shared between several users (e.g. a family), reasonably secure, but less private and prone to hardware malfunction
> 2. the device's PIN/password: no fine control and probably less secure, but it's robust 

Option 2 was missing from iOS, but fixed via this PR.

&nbsp;

If the user:
* enables biometrics (Face ID / Touch ID)
* but does not enable the passcode fallback
* and has not backed up their recovery phrase

then we display this warning:

### CODE REVIEW

**Comment by robbiehanson** [comment]
> I think we can just remove that warning altogether : users need to backup their seed regardless of the app-control setting. It's true that a broken biometrics hardware can lock the user out if the passcode fallback was disabled, but that's just an edge case among many and we can't handle all of them.

I agree. And that screen already displays a warning icon next to the "Recovery Phrase", if the user hasn't performed a backup.

Done in 880114a470a5b2793721d744479053cbad5fd15e

**Comment by robbiehanson** [comment]
> Is it possible to let the user only use the Passcode option, without having to enable FaceID/TouchID?

I do not believe this is possible. My understanding is that you have to use [LAContext](https://developer.apple.com/documentation/localauthentication/lacontext) to prompt for iOS authentication. And the supported [policies](https://developer.apple.com/documentation/localauthentication/lapolicy) only allow you to determine whether-or-not to allow passcode fallback.

**Comment by robbiehanson** [comment]
Addresses issue #455

**Review by dpad85 — APPROVED** [review]
LGTM

**Pull request merged**
