### PR TITLE
ar new strings

### PR DESCRIPTION
**Pull request by EZ0010**
Updated Arabic strings (the new iCloud backup strings and deleted some other not used strings).

### CODE REVIEW

**Comment by EZ0010** [comment]
As part of the localization of the wallet, is it possible to translate the website https://phoenix.acinq.co/faq?
I really want bitcoin adoption to reach everyone, and I believe translation will help.

would be really great to have all of the project fully translated even the FAQ questions which users may want to read.
I translated the site and added `<html lang="ar" style=" direction: rtl;">` to make it work for RTL languages and I don't see any issue.
Screen Shot 2022-01-27 at 10 32 59 PM

**Comment by dpad85** [comment]
Yes it's be possible to translate the FAQ as well. The content is a simple markdown file (https://phoenix.acinq.co/content/faq.md). It would need some work on the frontend but it can be done. The issue more about maintenance.

**Comment by EZ0010** [comment]
Cool! If anytime you decide to support multiple languages on the site I will be happy to do the Arabic translation on everything including redesigning the screenshots and the discerption on the AppStore & Google Play.
I know it is not priority for now but I believe it really help for adoption.

**Comment by robbiehanson** [comment]
Awesome !

**Pull request merged**
