### PR TITLE
Allow self-signed certificates for custom Electrum server

### PR DESCRIPTION
**Pull request by robbiehanson**
Fixes issue #182 

Notes: 
- This fixes the iOS build (matches latest lightning-kmp changes)
- This PR contains a **breaking change for Android**. In particular, in `ElectrumConfiguration.kt`:

```kotlin
// OLD:
sealed class Intent : MVI.Intent() {
  data class UpdateElectrumServer(val address: String?) : Intent()
}

// NEW
sealed class Intent : MVI.Intent() {
  data class UpdateElectrumServer(val server: ServerAddress?) : Intent()
}
```

So the difference here is that previously we passed a string, and the ElectrumConfigurationController handled parsing it to a ServerAddress. But now the client is expected to directly pass the ServerAddress. Which is because the `ServerAddress` class now allows you to pin a public key.

The solution for now (until Android implements custom UI for pubKey pinning) is to copy the old parsing code from `ElectrumConfigurationController`, which was something like this:

```kotlin
intent.address.matches("""(.*):(\d*)""".toRegex()) -> {
    intent.address.split(":").let {
        val host = it.first()
        val port = it.last()
        val serverAddress = ServerAddress(host, port.toInt(), TcpSocket.TLS.TRUSTED_CERTIFICATES)
     }
}
```

- This PR increases security by pinning the public keys for the default list of Electrum servers. (See `electrumConfs.kt`) To verify these pub key values, you can:

```
$ openssl s_client -connect testnet.qtornado.com:51002
``` 

^ This command will print the server's certificate to the console. (The part that starts with `-----BEGIN CERTIFICATE-----` and ends with `-----END CERTIFICATE-----`) Write that to a file (e.g. `testnet.qtornado.com.pem`). And then use this command to extract the public key from the certificate:

```
openssl x509 -in testnet.qtornado.com.pem -noout -pubkey
```

### CODE REVIEW

**Comment by dpad85** [comment]
I found an issue when testing this on testnet. Using address `testnet1.electrum.acinq.co` with port `51002`, I got the following message : `Server certificate is trusted` after clicking on `Save`, but no info about the certificate. And then I'm stuck because the `Save` button does not do anything, and the `Cancel` button just closes the sheet without saving my custom server.

**Comment by robbiehanson** [comment]
Good catch! Fixed in [01f5078](https://github.com/ACINQ/phoenix/pull/272/commits/01f507852aa087cd9225c5d44a9a2850249bf5b1)

**Comment by dpad85** [comment]
A few nitpicks: the icon used to cycle through the certificate fields is a bit strange (it's usually an icon used to reply). Maybe we could use arrows like this:
image
image


Also, if the certificate is invalid, it might be nice to also print an error message below the `Connecting to xxxx`, in the electrum server screen.

**Comment by robbiehanson** [comment]
> the icon used to cycle through the certificate fields is a bit strange (it's usually an icon used to reply).

Yeah, that's a good point. Changed it to this one:

Screen Shot 2022-05-13 at 09 46 43

**Comment by robbiehanson** [comment]
> Also, if the certificate is invalid, it might be nice to also print an error message below the Connecting to xxxx, in the electrum server screen.

Added notice:

Screen Shot 2022-05-13 at 10 10 55

And we have a NoticeBox on the HomeView, since the user might not think to check the settings:

164541124-6fd9282f-8c07-45e3-80c8-300e27c8f27e

**Pull request merged**
