### PR TITLE
Adding ability to backup recovery phrase in iCloud

### PR DESCRIPTION
**Pull request by robbiehanson**
## Major UI changes:

As per issue #204, the "Recovery phrase" section has been merged into the "Backup" section:

There are better warnings about backing up your recovery phrase. And the "Manual backup" option allows you mark the task as done:

The new "iCloud backup" option:

And the new "restore wallet" flow:

## Major code changes:

- The old `SyncManager` (which handled transactions) has been renamed `SyncTxManager`
- There's a new `SyncSeedManager`
- And the shared code (monitoring the network, monitoring iCloud account status) has been moved into a shared `SyncManager`

## Remaining work (for future PR):

- Issue #205 - Link to backup on the home screen

### CODE REVIEW

**Comment by dpad85** [comment]
Looks good 👍  In fact those screens looks so good that it prompted me to rework the design of the new android app to be more inline with the iOS app

**Comment by robbiehanson** [comment]
:blush: I had help from the bitcoin design team.

**Comment by robbiehanson** [comment]
In another branch I've added the backup-link from the HomeView:



I want to keep these changes separate from this branch to simplify the review process. So I will wait until this branch has been merged.

**Comment by robbiehanson** [comment]
Force-pushed because the original commit wasn't signed

**Review by dpad85 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
