### PR TITLE
feat: add MXN exchange rate from bitso API

### PR DESCRIPTION
**Pull request by mautematico**

### CODE REVIEW

**Comment by dpad85** [comment]
I'll need some time to review this, but this is a good idea, and we need to support additional currencies.

**Comment by mautematico** [comment]
is there anything I can do to help getting this merged?

**Comment by dpad85** [comment]
Not really, I just have to test your PR. I'll try to do that tomorrow!

**Comment by dpad85** [comment]
Thanks for the PR! I've seized the opportunity and improved a few things related to fiat handling, including the method saving a fiat rate into the preferences.

**Pull request merged**
