### PR TITLE
Full translation of Phoenix into Czech completed.

### PR DESCRIPTION
**Pull request by MasterixCZ**
+ Small corrections in important_strings.xml
+ strings.xml  -  Phoenix is now fully localized into Czech.

### CODE REVIEW

**Review by dpad85 — APPROVED** [review]
Looks good, thanks!

**Comment by MasterixCZ** [comment]
👍🏻

**Comment by margre8** [comment]
The translation is great! Thank you @MasterixCZ

**Comment by MasterixCZ** [comment]
@margre8 thank you :)

**Pull request merged**
