### PR TITLE
Add and translate new strings to Portuguese Brazilian

### PR DESCRIPTION
**Pull request by bitcoinuser**

### CODE REVIEW

**Comment by dpad85** [comment]
Thanks @bitcoinuser Unfortunately I won't be able to add it to the release.

**Comment by bitcoinuser** [comment]
> Thanks @bitcoinuser Unfortunately I won't be able to add it to the release.

I didn't understand. What is the reason?

**Comment by dpad85** [comment]
It's just that the release containing the feature is already made, so your translations will only be added in the release that one.

**Comment by bitcoinuser** [comment]
> It's just that the release containing the feature is already made, so your translations will only be added in the release after that one.

Understood. Thanks

**Review by dpad85 — APPROVED** [review]

**Pull request merged**
